### ISSUE TITLE
BaristaRule runs tests before activity is visible

### ISSUE THREAD

**Issue by kenyee** [SchibstedSpain/Barista#299] opened 2019-05-16 19:06 UTC
**Library Version:**

2.10.0
  
**Describe the Bug:**

BaristaRule seems to launch your Espresso UI test before the activity is displayed.

**Steps to reproduce the bug:**

Code looks like this:
```
@RunWith(AndroidJUnit4::class)
@LargeTest
class BasicSearchTest : BaseSearchTest() {
    @get:Rule
    var baristaRule: BaristaRule<SearchActivity> = BaristaRule.create(SearchActivity::class.java)

    @Repeat(times = 1)
    @Test
    @Throws(Exception::class)
    fun searchStuff() {
```

1. put a breakpoint in your test
2. watch the emulator screen
3. notice that you breakpoint gets hit before the activity is displayed
4. the first clickOn() in your test will fail

FlakyTestRule also doesn't work for the same reason...activity isn't displayed yet when it starts running your test.

Current code that does work but doesn't have the retry behavior I wanted:
```
    @get:Rule
    var mActivityRule = ActivityTestRule(
            SearchActivity::class.java)

    @Test
    @Throws(Exception::class)
    fun searchStuff() {
```

**Expected Behavior:**

Activity in rule should be displayed before your test is called.

**Comment by Sloy** [comment] 2019-05-16 19:40
Hi @kenyee. I think you're describing the intended behaviour.
There's a difference between `ActivityTestRule` and `BaristaRule`. 
`ActivityTestRule` starts the Activity by default before the test start. This causes some issues with the special Rules in Barista. For that reason, `BaristaRule` doesn't start the activity until you manually do it.

In short, you should invoke `baristaRule.launchActivity())` before interacting with the UI.

**Comment by Sloy** [comment] 2019-05-17 08:57
I'm closing this. Feel free to reopen if you see it's still not working.

**Closed by Sloy** 2019-05-17 08:57 UTC
